---
layout: post
title:  "Groups"
categories: homework
---

We have divided you into groups based on the first letter of your last name. A file containing all group data is available [here](https://raw.githubusercontent.com/sebastianbarfort/sds/master/data/groups.csv). 

```{r, eval = FALSE, echo = FALSE}
library("readxl")
library("dplyr")

df = read_excel("~/git/sds/data/participants.xlsx", col_names = FALSE)
df$group = rep(1:27, each = 4)[-108]

names(df) = c("name", "role", "group")

# add late enrollments
df2 = read_excel("~/git/sds/data/participants1.xlsx", 
                 col_names = FALSE)
df2$indicator = "new"

df = full_join(df, df2, by = c("name" = "X1"))

# manually remove students who won't take the exam
# søren korsgaard
df = df[-grep("korsgaard", tolower(df$name)), ]
# peter pallesen
df = df[-grep("pallesen", tolower(df$name)), ]
# marina canta
df = df[-grep("canta", tolower(df$name)), ]

# meisel
df = df[-grep("meisel", tolower(df$name)), ]

# helander 
df = df[-grep("pernille helander", tolower(df$name)), ]

# Golovchenko
df = df[-grep("golovchenko", tolower(df$name)), ]
# Anders Daugaard 
df = df[-grep("anders daugaard", tolower(df$name)), ]

# Foltinger
df = df[-grep("foltinger", tolower(df$name)), ]

# Sørensen, Asger Johannes Bay 
df = df[-grep("johannes bay", tolower(df$name)), ]

# change Stentoft-Hansen, Valdemar
df$group[grep("stentoft-hansen", tolower(df$name))] = 27

# sophie burgard: group 24
# linxin chen: group 24
df$group[grep("burgard", tolower(df$name))] = 24
df$group[grep("chen", tolower(df$name))] = 24

# peter harum: group 3
df$group[grep("haurum", tolower(df$name))] = 3

# the rest: group 28
df$group[is.na(df$group)] = 28

# merge groups 7 & 20
df$group[df$group == 20] = 7

df = df %>% 
  select(name, X2, group) %>%
  rename(role = X2) %>%
  arrange(group) %>%
  group_by(group) %>%
  mutate(
    group.count = n()
  )

library("DT")
df$group.count = NULL
name  = df$name
df = df[, -1]
rownames(df) = name
knitr::kable(df)

# group 7:
# |Golovchenko, Yevgeniy Yevgeniyovych |Student |     7|
# |Hansen, Anders Daugaard             |Student |     7|

# group 6?
# |Foltinger, Astrid Willum            |Student |     6|

# group 24: 
#|Sepúlveda Witt, Guillermo Edgardo   |Student |    24|
#|Svensson, Emily Mae                 |Student |    24|
#|Sørensen, Asger Johannes Bay        |NA      |    24|

# group 26: 
# - Villumsen, Signe Gro Møller 
# - Werkstetter, Tobias
```

The groups are as follows: 


|                                    |role    | group|
|:-----------------------------------|:-------|-----:|
|Albrechtsen, Kasper Hjalager        |Student |     1|
|Almdal, Nynne Helt                  |Student |     1|
|Andersen, Stine Hindberg            |Student |     1|
|Arimany Freixa, Julia               |Student |     1|
|Bach, Anna Cecilie Friis            |Student |     2|
|Belmouhand, Samira                  |Student |     2|
|Bjerg, Simon Kjær                   |Student |     2|
|Bjørn, Rasmus                       |Student |     2|
|Brodersen, Emil Regin               |Student |     3|
|Busch, Frederik Oliver              |Student |     3|
|Carlsen, Rolf Kranold               |Student |     3|
|Haurum, Peter                       |Student |     3|
|Caspersen, Sune Christian           |Student |     4|
|Christensen, Nina Holst             |Student |     4|
|Christiansen, Chris Cornelia Friis  |Student |     4|
|Christoffersen, Jeppe Brødegaard    |Student |     4|
|Dalsten, Mathias                    |Student |     5|
|Dammeyer, Anne                      |Student |     5|
|Djernes, Morten Randløv             |Student |     5|
|Eck Poulsen, Kristina               |Student |     5|
|Egerod, Benjamin Carl               |Student |     6|
|Elberg, Ulrik Torp                  |Student |     6|
|Eriksson, Simon                     |Student |     6|
|Gallagher, Neil Justin              |Student |     7|
|Goldschmidt, Peter Riemer           |Student |     7|
|Olsen, Sascha                       |Student |     7|
|Pedersen, Jesper Hybel              |Student |     7|
|Hansen, Ann-Sofie                   |Student |     8|
|Hansen, Dennis                      |Student |     8|
|Hansen, Susanne Sundgaard           |Student |     8|
|Harmsen, Oskar                      |Student |     8|
|Harslund, Mads Wulff                |Student |     9|
|Hidan, Lukas Nabil                  |Student |     9|
|Hjartar, Hjörtur Pall               |Student |     9|
|Holm, Rasmus Gars                   |Student |     9|
|Horsted, Sophie Wenzel              |Student |    10|
|Højfeldt, Julie Paprika             |Student |    10|
|Iversen, Anna Kollerup              |Student |    10|
|Jensen, Rasmus Rahbek               |Student |    10|
|Jeppesen, Trine Sun                 |Student |    11|
|Joensen, Jákup Dam                  |Student |    11|
|Johansen, Jo Brun                   |Student |    11|
|Kim, Jane                           |Student |    11|
|Klingler, Timo Oliver               |Student |    12|
|Koch, Tanja                         |Student |    12|
|Koehn, Margaret                     |Student |    12|
|Kristiansen, Ida Lykke              |Student |    13|
|Kruithof, Bob                       |Student |    13|
|Lam, Chuk Yat                       |Student |    13|
|Lange, Mette                        |Student |    13|
|Langholz, Andreas Als               |Student |    14|
|Lassen, Anne Sophie Schytt          |Student |    14|
|Lemaitre, Philip Stefan Puge        |Student |    14|
|Lillemæhlum, Dominik Zdyb           |Student |    14|
|Linnemann, Adam Frederik Ingwersen  |Student |    15|
|Lycke, Jesper                       |Student |    15|
|Mammen, Mathilde Else Ripka         |Student |    15|
|Marschall, Laurits                  |Student |    15|
|Mathiasen, Benjamin Wedel           |Student |    16|
|Mertz, Mikkel Baggesgaard           |Student |    16|
|Mogensen, Bjarke Dahl               |Student |    16|
|Mortensen, Caroline Mark            |Student |    17|
|Mróz, Michal                        |Student |    17|
|Møller, Anna Kristin                |Student |    17|
|Møller-Haastrup, Tamara             |Student |    17|
|Nielsen, Anders Woller              |Student |    18|
|Nielsen, Cæcilie Venzel             |Student |    18|
|Nielsen, Jens Ødum                  |Student |    18|
|Nielsen, Thorstein Torbenson        |Student |    18|
|Nielsen, Yanli Xu                   |Student |    19|
|Nygaard, Christoffer Braüner        |Student |    19|
|Olesen, Daniel Sloth                |Student |    19|
|Olesen, Simon Alexander             |Student |    19|
|Peterson, Søren Bo                  |Student |    21|
|Peus, Christian                     |Student |    21|
|Ponikowski, Charlotte               |Student |    21|
|Poulsen, Hallur                     |Student |    21|
|Poulsen, Louise                     |Student |    22|
|Pugesgaard, Kaspar Grøn             |Student |    22|
|Rasmussen, Kasper Wetterslev        |Student |    22|
|Rasmussen, Line Vodby               |Student |    22|
|Rauf, Thamina                       |Student |    23|
|Ruhnau, Rasmus                      |Student |    23|
|Sandoy, Trondur Møller              |Student |    23|
|Schondelmaier, Martin               |Student |    23|
|Sepúlveda Witt, Guillermo Edgardo   |Student |    24|
|Svensson, Emily Mae                 |Student |    24|
|Burgard, Sophie                     |Student |    24|
|Chen, Linxin                        |Student |    24|
|Thaysen, Natasha Reimer             |Student |    25|
|Thomsen, Aksel                      |Student |    25|
|Thomsen, Niels Petter               |Student |    25|
|Vallebo, Hans Peter                 |Student |    25|
|Vestergaard, Claus Enevold Ringtved |Student |    26|
|Villumsen, Signe Gro Møller         |Student |    26|
|Werkstetter, Tobias                 |Student |    26|
|Werlauff, Kasper Skærlund           |Student |    26|
|Stentoft-Hansen, Valdemar           |Student |    27|
|Wesselhoff, Stine Lund              |Student |    27|
|Ziegler, Robert Mark                |Student |    27|
|Østergaard, Esben                   |Student |    27|
|Jensen, Tor                         |Student |    28|
|Pedersen, Jens-Peter Serup          |Student |    28|
|Wiget, Janette                      |Student |    28|
|Ye, Chuou                           |Student |    28|

