---
layout: post
title:  "Topic 4: Introduction to Programming"
categories: homework
---

> This is the job. - Lester Freamon

> being a programmer means feeling stupid all the time, but less stupid than a year ago.

Links:

- http://www.slideshare.net/jenniferbryan5811/ubc-stat545-2014-cm001-intro-tocourse?related=1


**general**

- http://www.compjour.org/
- https://gist.github.com/hadley/820f09ded347c62c2864

**Browse before class**

- Lazer, David, et al. 2009. ''[Computational Social Science](http://www.sciencemag.org/content/323/5915/721.summary)''. *Science*. 323(5915): 721-723. ([Open access version](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2745217/)).
- Edelman, Benjamin. 2012. [''Using Internet Data for Economic Research''](http://pubs.aeaweb.org/doi/pdfplus/10.1257/jep.26.2.189), *Journal of Economic Perspectives*, 26(2): 189-206.

**Suggested readings**

- Ch. 1: Spraul, V. Anton. 2012. *Think like a
Programmer*. San Francisco: No Starch Press.
- Blackwell, Matthew, and
Maya Sen. 2012. [''Large Datasets and You: A Field Guide''](http://scholar.harvard.edu/files/msen/files/blackwell_sen_tpm.pdf), *The Political Methodologist* 20(1): 2-5.
- Wickham, Hadley. 2014. [''Tidy Data''](http://www.jstatsoft.org/v59/i10). *Journal of Statistical Software*, 59(10): 1–23.
- Leek, Jeff. 2014. [''How to share data with a statistician''](https://github.com/jtleek/datasharing).
- Shotts Jr., William E. 2012. ''The Linux Command Line: A complete introduction''. No Starch Press, San Fransisco.
- [RegexOne](http://regexone.com/).
- [Eight Terminal Utilities Every OS X Command Line User Should Know](http://www.mitchchn.me/2014/os-x-terminal/).
- [Strings - Dive into Python 3](http://www.diveintopython3.net/strings.html).


** data science**

- http://www.kdnuggets.com/2015/07/data-science-degrees-analyzed.html
- http://bulletin.imstat.org/2014/09/data-science-how-is-it-different-to-statistics%E2%80%89/
- http://www.chalmers.se/en/areas-of-advance/ict/events/Documents/Terry%20Speed_Data%20Science,%20Big%20Data%20and%20Statistics%20-%20Can%20We%20All%20Live%20Together.pdf
- https://dl.dropboxusercontent.com/u/41902/future-da-5-unconf.pdf
